name: x_validators
description: Simple, composable, zero-dependency form and text validation for Dart and Flutter. Stack rules and plug straight into TextFormField.
version: 1.2.0
homepage: https://github.com/Eng-MahmoudBasuony/x_validators
repository: https://github.com/Eng-MahmoudBasuony/x_validators
issue_tracker: https://github.com/Eng-MahmoudBasuony/x_validators/issues

topics:
  - validation
  - validator
  - forms
  - form-validation
  - flutter


environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.4
