name: x_validators
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/Eng-MahmoudBasuony/x_validators
repository: https://github.com/Eng-MahmoudBasuony/x_validators


environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
